[profile.default]
# solc_version = '0.8.13'
solc_version = '0.8.9'
src = 'chaintrap'
test = 'tests/forge/tests'
out = 'build/forge/out'
libs = ['node_modules']
verbosity = 4

[profile.hardhat]
src = 'chaintrap'
out = 'build/forge/out'
libs = ['node_modules']

# See more config options https://github.com/gakonst/foundry/tree/master/config
