[profile.default]
ffi = true
solc_version = "0.8.22"
optmizer = true
# optmizer_runs = 200
src = 'chaintrap'
test = 'tests/forge'
out = 'build/forge'
cache_path = 'cache/forge'
libs = ["node_modules", "lib"]
verbosity = 4
# fs_permissions = [{ access = "read-write", path = "./"}]
fs_permissions = [
    { access = "read", path = "build/forge/DiamondLoupeFacet.sol"},
    { access = "read", path = "build/forge/OwnershipFacet.sol"},
    { access = "read", path = "build/forge/ERC165Facet.sol"},
    { access = "read", path = "build/forge/ERC173Facet.sol"},
    { access = "read", path = "build/forge/ArenaFacet.sol"},
    { access = "read", path = "build/forge/ArenaCalls.sol"},
    { access = "read", path = "build/forge/ArenaERC1155.sol"},
    { access = "read", path = "build/forge/ArenaTranscripts.sol"},
    ]

[profile.hardhat]
src = 'chaintrap'
out = 'build/forge'
libs = ['node_modules']
[rpc_endpoints]
opsepolia = "${SEPOLIA_RPC_URL}"
[etherscan]
opsepolia = { key = "${ETHERSCAN_API_KEY}", url = "${ETHERSCAN_URL}" }

# See more config options https://github.com/gakonst/foundry/tree/master/config
