[profile.default]
# solc_version = '0.8.13'
solc_version = '0.8.9'
optmizer = true
# optmizer_runs = 200
src = 'chaintrap'
test = 'tests/forge/tests'
out = 'build/forge/out'
libs = ["node_modules", "lib"]
verbosity = 4
# fs_permissions = [{ access = "read-write", path = "./"}]
fs_permissions = [
    { access = "read", path = "build/forge/out/DiamondLoupeFacet.sol"},
    { access = "read", path = "build/forge/out/OwnershipFacet.sol"},
    { access = "read", path = "build/forge/out/ERC165Facet.sol"},
    { access = "read", path = "build/forge/out/ERC173Facet.sol"},
    { access = "read", path = "build/forge/out/ArenaFacet.sol"},
    { access = "read", path = "build/forge/out/ArenaCalls.sol"},
    { access = "read", path = "build/forge/out/ArenaERC1155.sol"},
    { access = "read", path = "build/forge/out/ArenaTranscripts.sol"},
    ]

[profile.hardhat]
src = 'chaintrap'
out = 'build/forge/out'
libs = ['node_modules']
[rpc_endpoints]
opsepolia = "${SEPOLIA_RPC_URL}"
[etherscan]
opsepolia = { key = "${ETHERSCAN_API_KEY}", url = "${ETHERSCAN_URL}" }

# See more config options https://github.com/gakonst/foundry/tree/master/config
