---
version: '3'
silent: true

# tasks are primarily for actions local to this repository. task is for things
# that usually don't need options (or can be configured once via a .env) use it
# especially when you have things that depend on other things

tasks:
  build:
    desc: build the npm package
    cmds:
      - npm run build
  test:
    desc: run the forge and hardhat tests
    cmds:
      - forge test -vvv && npx hardhat test
