// SPDX-License-Identifier: UNLICENSED
pragma solidity =0.8.9;

error Transcript_IsInitialised();
error Transcript_IsInvalid();
error Transcript_IsComplete();
error Transcript_NotReady();
error Transcript_NotCompletable();
error Transcript_NotStarted();
error Transcript_RegistrationFull();
error Transcript_ParticipantHalted();
error Transcript_InvalidChoice();
error Transcript_InvalidStartChoice();
error Transcript_TwoTransitionTypesRequired();
error Transcript_ChoiceInputTypeRequired();
error Transcript_VictoryTransitionTypeRequired();
error Transcript_ChoiceSetTypeInvalid();
error Transcript_TransitionTypeInvalid();
error Transcript_RegistrationClosed();
error Transcript_EarlierPendingOutcomeExists();
error Transcript_AlreadyRegistered();
error Transcript_NotRegistered();
error Transcript_VerifyFailed();
error Transcript_OutcomeNotProven();
error Transcript_OutcomePending();
error Transcript_InvalidRootLabel();
error Transcript_InvalidEntry();
error Transcript_OutcomeIllegal();
error Transcript_OutcomeExpectedProof();
error Transcript_OutcomeVerifyFailed();
