on:
  push:
  #  tags:
  #    - 'v[0-9]+.[0-9]+.[0-9]+'

name: ci

jobs:
  test:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          path: chaintrap-contracts
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install go-tusk and go-task
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin

          # go-task
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- \
            -d -b $GITHUB_WORKSPACE/bin
          echo $GITHUB_WORKSPACE/bin >> $GITHUB_PATH

      - name: Install contract dependencies and hh test deps
        working-directory: chaintrap-contracts
        run: |
          # ensure we are using the latest packaged source, going forward we
          # want the ci builds to depend only on published packages. for
          # diamond-deploy we do want to force the latest for now.
          npm uninstall --save "@polysensus/diamond-deploy"
          npm install "@polysensus/diamond-deploy@latest"
          npm install

      - name: build 
        working-directory: chaintrap-contracts
        run: task build DIAMOND_DEPLOY="npx @polysensus/diamond-deploy"

      - name: Run forge tests
        working-directory: chaintrap-contracts
        run: task test:forge

      - name: Run hardhat tests
        working-directory: chaintrap-contracts
        run: task test:hh

      - name: publish npm package
        working-directory: chaintrap-contracts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: contains(github.ref, 'refs/tags/') && github.event_name == 'push'
        #if: ${{ startsWith(github.event.head_commit.message, 'release:v') ||
        #          startsWith(github.event.head_commit.message, 're-release:') ||
        #          startsWith(github.event.head_commit.message, 'fix:') }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" > ~/.npmrc

          tree dist abi

          # github has scale issues when there are a large (> 20 ) npm packages in
          # a repo, so force for fixes seems like the right thing for now.
          FORCE=""
          if [[ ! $(git log -1 --pretty=%B) =~ '^release:v' ]]; then
            export FORCE=--force
          fi
          npm publish $FORCE

      - name: package cleanup
        # note this hasn't been tested yet
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/delete-package-versions@v4
        if: contains(github.ref, 'refs/tags/') && github.event_name == 'push'
        # if: ${{ startsWith(github.event.head_commit.message, 'release:v') ||
        #           startsWith(github.event.head_commit.message, 're-release:') ||
        #           startsWith(github.event.head_commit.message, 'fix:') }}
        with:
          package-name: "chaintrap-contracts"
          package-type: "npm"
          min-versions-to-keep: 5

