on: [push]

name: ci

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install contract dependencies and hh test deps
        run: npm install
      - name: Run forge tests
        run: forge test -vvv

      - name: Run hardhat tests
        run: npx hardhat test
      - name: publish npm package
        env:
          PAT_PACKAGE_WRITE: ${{ secrets.PAT_PACKAGE_WRITE }}
        run: |
          #[ -z "$PAT_PACKAGE_WRITE" ] && echo "PAT_PACKAGE_WRITEn ot set" && exit 1
          #echo "//npm.pkg.github.com/:_authToken=$PAT_PACKAGE_WRITE" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" > ~/.npmrc
          npm publish

