on:
  push:

name: ci

jobs:
  test:
    name: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          path: chaintrap-contracts
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install go-tusk and go-task
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin

          # go-task
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- \
            -d -b $GITHUB_WORKSPACE/bin
          echo $GITHUB_WORKSPACE/bin >> $GITHUB_PATH

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          scope: "@polysensus"
          registry-url: "https://registry.npmjs.org"

      - name: install packages
        working-directory: chaintrap-contracts
        run: |
          npm install
      - name: build 
        working-directory: chaintrap-contracts
        run: |
          mkdir -p .local/out-tsc
          task build

      - name: Run forge tests
        working-directory: chaintrap-contracts
        run: task test:forge

      - name: Run hardhat tests
        working-directory: chaintrap-contracts
        run: task test:hh