on: [push]

name: ci

jobs:
  test:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install contract dependencies and hh test deps
        run: npm install

      - name: Run forge tests
        run: forge test -vvv

      - name: Run hardhat tests
        run: npx hardhat test
  publish:
    name: Publish
    needs: test
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push'
      && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' )
      && contains(github.event.head_commit.message, 'release: v') == true
    steps:
    - uses: actions/checkout@v2
    - name: Cache node_modules
      id: cache-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: 16.x-${{ runner.OS }}-build-${{ hashFiles('package.json') }}
    - name: Build
      if: steps.cache-modules.outputs.cache-hit != 'true'
      run: npm install
    #- name: Test
    #  run: npm_config_yes=true npx best-test@latest
    - name: Auth via npmrc for pkg.github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" > ~/.npmrc

    - name: Publish
      uses: mikeal/merge-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_REGISTRY_URL: https://npm.pkg.github.com

     #  this needs to go in a release action OR we need to continualy
     #  delete/overwrite the current release
     #- name: publish npm package
     #  env:
     #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     #  run: |
     #    echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" > ~/.npmrc
     #    npm publish

