on: [push]

name: ci

jobs:
  test:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install go-tusk and go-task
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin

          # go-task
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- \
            -d -b $GITHUB_WORKSPACE/bin
          echo $GITHUB_WORKSPACE/bin >> $GITHUB_PATH

      - name: Install contract dependencies and hh test deps
        run: npm install

      - name: build 
        run: task build

      - name: Run forge tests
        run: task test:forge

      - name: Run hardhat tests
        run: task test:hh

  publish:
    name: Publish
    needs: test
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'release - v')
    #if: |
    #  github.event_name == 'push'
    #  && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' )
    #  && contains(github.event.head_commit.message, 'release: v')
    steps:
    - uses: actions/checkout@v2
    - name: Cache node_modules
      id: cache-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: 16.x-${{ runner.OS }}-build-${{ hashFiles('package.json') }}
    - name: Build npm package
      if: steps.cache-modules.outputs.cache-hit != 'true'
      run: npm install

    - name: publish npm package
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" > ~/.npmrc
        npm publish

